name: Deploy Widgets to Testnet
on:
  push:
    branches: [develop]
jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    name: Deploy widgets to discom.testnet
    env:
      NEAR_SOCIAL_ACCOUNT_ID: ${{ vars.NEAR_SOCIAL_TESTNET_ACCOUNT_ID }}
      NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY: ${{ vars.NEAR_SOCIAL_TESTNET_ACCOUNT_PUBLIC_KEY }}
      NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY: ${{ secrets.NEAR_SOCIAL_TESTNET_ACCOUNT_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install near-social CLI
        run: |
          sudo apt install -y pkg-config libusb-1.0-0-dev libftdi1-dev
          sudo apt-get install libudev-dev
          cargo install --git https://github.com/FroVolod/near-social --branch required-deposit

      - name: Deploy widgets
        run: |
          which near-social
          echo $PATH
          ~/.cargo/bin/near-social deploy "$NEAR_SOCIAL_ACCOUNT_ID" sign-as "$NEAR_SOCIAL_ACCOUNT_ID" network-config testnet sign-with-plaintext-private-key --signer-public-key "$NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY" --signer-private-key "$NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY" send
